name: common-labels

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

env:
  REPO: ${{ github.repository }}
  COMMON_REPO: fabien-marty/common
  ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  sync-labels:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write
    steps:
      - name: Check out ${{ env.COMMON_REPO }} code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: ${{ env.COMMON_REPO }}
          persist-credentials: false
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ env.ACCESS_TOKEN }}
      - name: Sync labels
        run: |
          cd labels
          task apply
